ALTER TABLE area ADD COLUMN image VARCHAR(255) DEFAULT NULL;

ALTER TABLE tables ADD COLUMN code VARCHAR(20) UNIQUE;

ALTER TABLE tables DROP COLUMN table_number;

ALTER TABLE tables ADD COLUMN seatNumber INT DEFAULT 4;

-- Create tableReservation table
CREATE TABLE IF NOT EXISTS tableReservation (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tableId INT NOT NULL,
    reservationTime DATETIME NOT NULL,
    customerId INT NULL,
    phone VARCHAR(100) NOT NULL,
    customerName VARCHAR(100) NOT NULL,
    is_deleted TINYINT (1) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tableId) REFERENCES tables (id),
    FOREIGN KEY (customerId) REFERENCES users (id)
);